[project]
name = "synformer"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [
    {name = "Wenhao Gao", email = "gaowh19@gmail.com"},
    {name = "Shitong Luo", email = "luost26@gmail.com"},
    {name = "Connor W. Coley", email = "ccoley@mit.edu"}
]
description = "SynFormer: Generative Model for Synthesizable Molecule Generation"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version", "dependencies"]


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "synformer.__version__" }
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
where = ["."]
include = ["synformer", "synformer.*"]

[tool.setuptools.package-data]
"synformer" = ["*.md", "*.txt", "*.csv", "data/*"]



[tool.black]
line-length = 119
target-version = ['py310']

[tool.isort]
extra_standard_library = "typing_extensions,mypy,mypy_extensions"
profile = "black"

[tool.autoflake]
remove-all-unused-imports = true
expand-star-imports = true
ignore-init-module-imports = true
